themesite/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace themesite.Controllers
{
    public class TestsController : Controller
    {

        u0506100_redexsrvdbEntities entity = new u0506100_redexsrvdbEntities();

        // GET: Test
        public ActionResult Index()
        {
            ViewBag.Title = "Начало";
            return View();
        }

        public ActionResult TestAction1()
        {
            ViewBag.Title = "Проверка - 1";
            return View();
        }

        public ActionResult MenuTest()
        {
            ViewBag.Title = "Тестирование меню";
            return View();
        }

        public ActionResult SideMenu()
        {
            ViewBag.Title = "SideMenu";

            List<Models.MenuItem> list = new List<Models.MenuItem>
            {
                new Models.MenuItem { Link = "/Tests/Index", LinkName = "Home" },
                new Models.MenuItem { Link = "/Tests/Login", LinkName = "Login" },
                new Models.MenuItem { Link = "/Tests/Registration", LinkName = "Register" }
            };
            return PartialView("SideMenu", list);
        }

        public ActionResult GetMenuList()
        {
            try
            {
                var result = (from m in entity.MenuTrees
                              select new Models.MenuListItem
                              {
                                  Id = m.M_ID,
                                  ParentId = m.M_P_ID,
                                  Name = m.M_NAME,
                                  ControllerName = m.CONTROLLER_NAME,
                                  ActionName = m.ACTION_NAME,
                                  CssClass = m.CSS_CLASS,
                                  HasChilds = false,
                                  IsRootElement = false,
                                  SortOrder = m.SORT_ORDER
                              })
                              .Distinct()
                              .ToList();

                var childs = result.Where(x => x.Id > 1 && x.ParentId > 1).ToList();

                foreach (var m in result)
                {
                    m.HasChilds = childs.Where(x => x.ParentId == m.Id).Count() > 0;
                    m.IsRootElement = !m.HasChilds && m.ParentId <= 1;
                }

                var menu = result.Where(x => x.Id > 1).OrderBy(x => x.SortOrder).Distinct().ToList();

                return PartialView("Menu", menu);
            }
            catch (Exception ex)
            {
                var error = ex.Message.ToString();

                if (ex.InnerException != null)
                {
                    error += Environment.NewLine;
                    error += ex.InnerException.Message;
                }

                Models.BaseModel model = new Models.BaseModel()
                {
                    HasErrors = true,
                    ErrorMessage = error
                };

                // return Content(@"<div> " + error + "</div>");
                return View(model);
            }

        }

    }

}

themesite/Views/Shared/_Layout - Default.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

themesite/Views/Shared/_LayoutTest.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="redexsrv services">
    <meta name="author" content="redexsrv">
    <meta name="keyword" content="">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>redexsrv - integration services</title>

    <!--

    <link href="Content/bootstrap.min.css" rel="stylesheet">

    <link href="Content/bootstrap-theme.css" rel="stylesheet">

    <link href="Content/elegant-icons-style.css" rel="stylesheet" />
    <link href="Content/font-awesome.min.css" rel="stylesheet" />

    <link href="assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" rel="stylesheet" />
    <link href="assets/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" />

    <link href="assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />

    <link rel="stylesheet" href="Content/owl.carousel.css" type="text/css">
    <link href="Content/jquery-jvectormap-1.2.2.css" rel="stylesheet">

    <link href="Content/fullcalendar.css" rel="stylesheet" />
    <link href="Content/widgets.css" rel="stylesheet" />
    <link href="Content/style.css" rel="stylesheet" />
    <link href="Content/style-responsive.css" rel="stylesheet" />
    <link href="Content/xcharts.min.css" rel=" stylesheet" />
    <link href="Content/jquery-ui-1.10.4.min.css" rel="stylesheet" />

    -->

    @Styles.Render("~/Content/css")
    @Styles.Render("~/assets/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    <!-- container section start -->
    <section id="container" class="">


        <header class="header dark-bg">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
            </div>

            <!--logo start-->
            <a href="/" class="logo"><span style="color:darkred;font-weight:600;">red</span>ex<span class="lite" style="color:#688a7e">srv</span></a>
            <!--logo end-->

            <div class="nav search-row" id="top_menu">
                <!--  search form start -->
                <ul class="nav top-menu">
                    <li>
                        <form class="navbar-form">
                            <input class="form-control" placeholder="Search" type="text">
                        </form>
                    </li>
                </ul>
                <!--  search form end -->
            </div>

            <div class="top-nav notification-row">
                <!-- notificatoin dropdown start-->
                <ul class="nav pull-right top-menu">

                    <!-- task notificatoin start -->
                    <!-- task notificatoin end -->
                    <!-- inbox notificatoin start-->
                    <!-- inbox notificatoin end -->
                    <!-- alert notification start-->
                    <!-- alert notification end-->
                    <!-- user login dropdown start-->
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="profile-ava">
                                    <img alt="" src="~/img/avatar1_small.jpg">
                                </span>
                                <span class="username">Jenifer Smith</span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu extended logout">
                                <div class="log-arrow-up"></div>
                                <li class="eborder-top">
                                    <a href="#"><i class="icon_profile"></i> My Profile</a>
                                </li>
                                <li>
                                    <a href="#"><i class="icon_mail_alt"></i> My Inbox</a>
                                </li>
                                <li>
                                    <a href="#"><i class="icon_clock_alt"></i> Timeline</a>
                                </li>
                                <li>
                                    <a href="#"><i class="icon_chat_alt"></i> Chats</a>
                                </li>
                                <li>
                                    <a href="login.html"><i class="icon_key_alt"></i> Log Out</a>
                                </li>
                                <li>
                                    <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
                                </li>
                                <li>
                                    <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
                                </li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="profile-ava">
                                    <img alt="" src="~/img/user.png">
                                </span>
                                <span class="username">Аккаунт</span>
                                <b class="caret"></b>
                            </a>

                            <ul class="dropdown-menu extended logout">
                                <div class="log-arrow-up"></div>
                                <li class="eborder-top">
                                    <a href="#"><i class="icon_profile"></i> Вход</a>
                                </li>
                                <li>
                                    <a href="#"><i class="icon_mail_alt"></i> Регистрация</a>
                                </li>
                            </ul>

                        </li>
                    }
                    <!-- user login dropdown end -->
                </ul>
                <!-- notificatoin dropdown end-->
            </div>
        </header>
        <!--header end-->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->

                @{ Html.RenderAction("GetMenuList", "Tests"); }

                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">

            <section class="wrapper">

                <div class="row">
                    <div class="col-lg-12">

                        @{ Html.RenderPartial("BreadCrumbs"); }

                    </div>
                </div>

                @RenderBody()

            </section>

        </section>

        <!--main content end-->
    </section>
    <!-- container section start -->
    <!-- javascripts -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <!--
    <script src="Scripts/jquery.js"></script>
    <script src="Scripts/jquery-ui-1.10.4.min.js"></script>
    <script src="Scripts/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="Scripts/jquery-ui-1.9.2.custom.min.js"></script>
    -->
    <!-- bootstrap
    <script src="Scripts/bootstrap.min.js"></script>
    -->
    <!-- nice scroll -->
    <script src="~/Scripts/jquery.scrollTo.min.js"></script>
    <script src="~/Scripts/jquery.nicescroll.js" type="text/javascript"></script>
    <!-- charts scripts -->
    <script src="~/assets/jquery-knob/js/jquery.knob.js"></script>
    <script src="~/Scripts/jquery.sparkline.js" type="text/javascript"></script>
    <script src="~/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="~/Scripts/owl.carousel.js"></script>
    <!-- jQuery full calendar -->
    <
    <script src="~/Scripts/fullcalendar.min.js"></script>
    <!-- Full Google Calendar - Calendar -->
    <script src="~/assets/fullcalendar/fullcalendar/fullcalendar.js"></script>
    <!--script for this page only-->
    <script src="~/Scripts/calendar-custom.js"></script>
    <script src="~/Scripts/jquery.rateit.min.js"></script>
    <!-- custom select -->
    <script src="~/Scripts/jquery.customSelect.min.js"></script>
    <script src="~/assets/chart-master/Chart.js"></script>

    <!--custome script for all page-->
    <script src="~/Scripts/scripts.js"></script>
    <!-- custom script for this page-->
    <script src="~/Scripts/sparkline-chart.js"></script>
    <script src="~/Scripts/easy-pie-chart.js"></script>
    <script src="~/Scripts/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/Scripts/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/Scripts/xcharts.min.js"></script>
    <script src="~/Scripts/jquery.autosize.min.js"></script>
    <script src="~/Scripts/jquery.placeholder.min.js"></script>
    <script src="~/Scripts/gdp-data.js"></script>
    <script src="~/Scripts/morris.min.js"></script>
    <script src="~/Scripts/sparklines.js"></script>
    <script src="~/Scripts/charts.js"></script>
    <script src="~/Scripts/jquery.slimscroll.min.js"></script>
    <script>
        //knob
        $(function () {
            $(".knob").knob({
                'draw': function () {
                    $(this.i).val(this.cv + '%')
                }
            })
        });

        //carousel
        $(document).ready(function () {
            $("#owl-slider").owlCarousel({
                navigation: true,
                slideSpeed: 300,
                paginationSpeed: 400,
                singleItem: true

            });
        });

        //custom select box

        $(function () {
            $('select.styled').customSelect();
        });

        /* ---------- Map ---------- */
        $(function () {
            $('#map').vectorMap({
                map: 'world_mill_en',
                series: {
                    regions: [{
                        values: gdpData,
                        scale: ['#000', '#000'],
                        normalizeFunction: 'polynomial'
                    }]
                },
                backgroundColor: '#eef3f7',
                onLabelShow: function (e, el, code) {
                    el.html(el.html() + ' (GDP - ' + gdpData[code] + ')');
                }
            });
        });
    </script>

    @RenderSection("scripts", required: false)

</body>

</html>